services:
  video-processor:
    build: ./video-processor
    environment:
      - INPUT_DIR=/app/storage/input
      - OUTPUT_DIR=/app/storage/processed
    volumes:
      - ./storage:/app/storage

  flower-recognizer:
    build: ./flower-recognizer
    environment:
      - OUTPUT_DIR=/app/storage/results
    volumes:
    volumes:
      - ./storage:/app/storage:ro

  dataset-matcher:
    build: ./dataset-matcher
    environment:
      - INPUT_DIR=/app/storage/results
    volumes:
      - ./storage:/app/storage:ro