# File: docker-compose.yml
services:
  video-processor:
    build: ./video-processor
    environment:
      - INPUT_DIR=/app/storage/input
      - OUTPUT_DIR=/app/storage/processed
    volumes:
      - ./storage/input:/app/storage/input
      - ./storage/processed:/app/storage/processed

  flower-recognizer:
    build: ./flower-recognizer
    environment:
      - OUTPUT_DIR=/app/storage/results
    volumes:
      - ./storage/processed:/app/storage/processed:ro
      - ./storage/results:/app/storage/results

  dataset-matcher:
    build: ./dataset-matcher
    environment:
      - INPUT_DIR=/app/storage/results
    volumes:
      - ./storage/results:/app/storage/results:ro